language: ruby
cache:
  bundler: true
  yarn: true
  directories:
     - /home/travis/.rvm/
rvm:
 - 2.6.3
before_install:
 - nvm install
install:
 - bundle install
 - yarn install
script:
 - bundle exec rails db:migrate
 - bundle exec rails test
