version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  ruby2: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    environment:
      BUNDLE_JOBS: "3"
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler:2.1
      # - ruby/bundle-install
      - ruby2/install-deps
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          command: yarn install
      - run:
          command: bundle exec rails db:migrate
      - save_cache: # Caches dependencies with a cache key
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - $CIRCLE_PROJECT_REPONAME
  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: bundle exec rails test
      - store_test_results:
          path: ~/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build